[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-bpf -p 10000 --cps partial --no-print-samples vbd.mc"
options = ""

[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-bpf -p 10000 --cps full --no-print-samples vbd.mc"
options = ""

[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-apf -p 10000 --cps partial --no-print-samples vbd.mc"
options = ""

[[app]]
runtime = "CorePPL2MExpr"
argument = "-m mexpr-apf -p 10000 --cps full --no-print-samples vbd.mc"
options = ""
