[[app]]
runtime = "PEADAE"
arguments = "--cse --numeric-jac --disable-peval furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --disable-peval furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --numeric-jac furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 0 furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 1 furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 2 furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 3 furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 4 furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 5 furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 6 furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 7 furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 8 furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 9 furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 10 furuta.dae"
options = "--output-only-last --interval 1000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[post]]
runtime = "id"
