[[app]]
runtime = "PEADAE"
arguments = "--cse --numeric-jac --disable-peval cauer_10.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --disable-peval cauer_10.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --numeric-jac cauer_10.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 0 cauer_10.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 1 cauer_10.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 2 cauer_10.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[post]]
runtime = "id"
