[[app]]
runtime = "PEADAE"
arguments = "--cse --numeric-jac --disable-peval pendulum.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --disable-peval pendulum.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --numeric-jac pendulum.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 0 pendulum.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 1 pendulum.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 2 pendulum.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[app]]
runtime = "PEADAE"
arguments = "--cse --jac-spec-absolute 3 pendulum.dae"
options = "--output-only-last --interval 10000 --step-size 1 --rtol 1.e-5 --atol 1.e-7"

[[post]]
runtime = "id"
