[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-res --disable-peval cauer_100.dae"
options = "11515"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-res --jac-spec-absolute 0 cauer_100.dae"
options = "11515"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-res --jac-spec-absolute 1 cauer_100.dae"
options = "11515"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-res --jac-spec-absolute 2 cauer_100.dae"
options = "11515"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-jac --disable-peval cauer_100.dae"
options = "29"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-jac --jac-spec-absolute 0 cauer_100.dae"
options = "29"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-jac --jac-spec-absolute 1 cauer_100.dae"
options = "29"

[[app]]
runtime = "PEADAE"
arguments = "--cse --benchmark-jac --jac-spec-absolute 2 cauer_100.dae"
options = "29"

[[post]]
runtime = "id"
